version: '3.8'

services:
  web:
    build:
      context: ..
    command: daphne -b 0.0.0.0 -p 8000 chat_project.asgi:application
    ports:
      - "8000:8000"
      - "8001:8001"
    volumes:
      - ../:/app
    env_file:
      - ../.env
    depends_on:
      - db
      - redis

  db:
    image: postgres:14
    env_file:
      - ../.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis-server
    ports:
      - "6379:6379"
    command: redis-server --requirepass supersecreta123
    volumes:
      - redis_data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf

volumes:
  postgres_data:
  redis_data:
